default_install_hook_types:
- pre-commit
- commit-msg

default_language_version:
  python: python3.11

repos:


# - repo: local
#   hooks:
#   - id: mypy
#     name: mypy
#     entry: python -m mypy --explicit-package-bases=stockmarket=src --show-error-codes
#     language: system
#     types: [python]
#     verbose: true
#     pass_filenames: true
#     # args: [ "--show-error-codes", "--config-file", "pyproject.toml",]

- repo: local
  hooks:
  - id: mypy
    name: mypy
    # Run in package mode and don't let pre-commit append filenames
    entry: mypy ./src/
    language: system
    types: [python]
    verbose: true
    pass_filenames: false
    args:
      - --show-error-codes
      - --disallow-untyped-defs
      - --disallow-incomplete-defs
      - --disallow-untyped-calls
      - --config-file
      -  pyproject.toml

- repo: local
  hooks:
  - id: mypy-tests
    name: mypy-tests
    entry: mypy ./tests/
    language: system
    types: [python]
    verbose: true
    pass_filenames: false


  - id: interrogate
    name: interrogate
    entry: interrogate
    language: system
    types: [python]
    args:
      - --fail-under=80
      - --verbose



  - id: ruff
    name: ruff-format
    entry: ruff format
    language: system
    types: [python]

  - id: ruff
    name: ruff linter
    entry: ruff check
    language: system
    types: [python]
    args: [--fix, --show-fixes, --exit-non-zero-on-fix] # Optionally: Automatically fix issues



- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-json
  - id: check-added-large-files
  - id: debug-statements
  - id: requirements-txt-fixer
  - id: check-yaml
  - id: sort-simple-yaml
  - id: check-added-large-files



# - repo: https://github.com/psf/black
#   rev: 25.11.0
#   hooks:
#   - id: black
#     language_version: python3.11
#     args:
#     - --config=pyproject.toml

- repo: https://github.com/asottile/pyupgrade
  rev: v3.17.0
  hooks:
  - id: pyupgrade


- repo: https://github.com/PyCQA/isort
  rev: 7.0.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    language_version: python3.11
    args:
    - --config=.flake8   # not pyproject.toml because of max-line-length issue

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.19.0
#   hooks:
#   - id: mypy
#     additional_dependencies: [
#       types-requests,
#     ]
#     args:
#     - --config-file=pyproject.toml
#     - --explicit-package-bases=src

- repo: https://github.com/pycqa/bandit
  rev: 1.9.2
  hooks:
  - id: bandit
    args: [ "-ll" ]
    files: .py$

- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.7
  hooks:
  - id: docformatter
    additional_dependencies: [tomli]
    args: [--in-place, --black]

- repo: https://github.com/numpy/numpydoc
  rev: v1.10.0
  hooks:
  - id: numpydoc-validation

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
  - id: shellcheck

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.46.0
  hooks:
  - id: markdownlint
    args: ["--fix"]

# - repo: https://github.com/JangasCodingplace/commit-prefix-pre-commit
#   rev: v0.0.3-beta
#   hooks:
#   - id: commit-prefix
#     stages: [ commit-msg ]

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.3.0
  hooks:
  - id: conventional-pre-commit
    stages: [ commit-msg ]
    args: [ ]
